### ISSUE TITLE
Add a tile engine

### ISSUE THREAD

**Issue by SimonMeskens** [CyprusGrunumn/RogueLike-Lite#1]
First issue!

You can close this issue with a commit by writing "fixes #1" in the description.
https://help.github.com/articles/closing-issues-using-keywords/

You can add this issue to milestones, you can use issues to write todo lists for features like. You can link to those issues from the roadmap. You can also label issues, like "bug", "feature", "suggestion", etc

As for tile engines, here's a really simple example:
http://silveiraneto.net/2008/04/27/simple-java-tileset-example/

You can easily adapt that tile engine for your game, if you need help with it, let me know. This might actually be a good time to create a branch. Create a branch called "tile-engine" and make it a PR (pull request). You can now make changes to that branch and people can comment on it and review it in the pull request. When you are done, you can press the "merge" button in the PR and it will be thrown into the master. Afterwards, you can delete the "tile-engine" branch.

I can walk you through how to make the branch and PR if you want

**Comment by CyprusGrunumn** [comment]
I'll be sure to start on this once I finish the tutorial. Thanks :D

**Comment by SimonMeskens** [comment]
Free tileset: https://opengameart.org/content/16x16-dawnhack-roguelike-tileset
